# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
  - task: Docker@1
    inputs:
      dockerFile: KL.HttpScheduler.Api/Dockerfile
      containerregistrytype: Azure Container Registry
      imageName: $(imageName)
      imageNamesPath: ''
      command: Build an image
      restartPolicy: no
