# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  tag: $(ACRNAME).azurecr.io/$(IMAGENAME)

steps:
  - bash: docker build -f ./KL.HttpScheduler.Api/Dockerfile -t $(tag) .
  - bash: docker login --username $(ACRNAME) --password $(ACRPASS) $(ACRNAME).azurecr.io
  - bash: docker push $(tag)
  - bash: redisid=`docker run -p 6379:6379 -d redis`
  - bash: dotnet test 
  - bash: docker stop $redisid