# Define the deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: '#{NAMESPACE}#'
  name: '#{API_IMAGENAME}#'
spec:
  replicas: #{Replicas}#
  selector:
    matchLabels:
      app: '#{API_IMAGENAME}#'
  template:
    metadata:
      labels:
        app: '#{API_IMAGENAME}#'
    spec:
      containers:
      - name: '#{API_IMAGENAME}#'
        image: '#{ACRNAME}#.azurecr.io/#{API_IMAGENAME}#:#{Build.SourceBranchName}#-#{Build.BuildId}#'
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: '#{ASPNETCORE_ENVIRONMENT}#'
          - name: ApplicationInsights__InstrumentationKey
            value: '#{InstrumentationKey}#'
          - name: Config__RedisConnectionString
            value: '#{RedisConnectionString}#'
        ports:
        - containerPort: 80
          name:  "http-port"
        readinessProbe:
          httpGet:
            path: /
            port: "http-port"
          initialDelaySeconds: 10
      imagePullSecrets:
        - name: '#{ACRNAME}#'

# Define the service to forward to above deployment
---
apiVersion: v1
kind: Service
metadata:
  namespace: '#{NAMESPACE}#'
  name: '#{API_IMAGENAME}#'
spec:
  selector:
    app: '#{API_IMAGENAME}#'
  ports:
  - name: "http-port"
    protocol: "TCP"
    port: 80

# Define the ingress
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: '#{NAMESPACE}#'
  name: '#{NAMESPACE}#-ingress'
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - #{HOST}#
    secretName: #{SECRETNAME}#
  rules:
  - host: #{HOST}#
    http:
      paths:
      - path: /scheduler/?(.*)
        backend:
          serviceName: #{API_IMAGENAME}#
          servicePort: "http-port"
